name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: pacman-contribution-graph.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_contrib_pacman: yes
